apps/cart/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from apps.cart.views import CartAddview, CartInfoView, CartUpdateView, CartDeleteView

app_name = 'apps.cart'
urlpatterns = [
    url(r'^add&', CartAddview.as_view(), name='add'),  # 购物车页面
    url(r'^$', CartInfoView.as_view(), name='cart'),  # 显示购物车页
    url(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车数据更新
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 删除购物车中的商品记录
]

apps/goods/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from apps.goods.views import IndexView, DetailView, ListView

app_name = 'apps.goods'
urlpatterns = [
    url(r'^index/$', IndexView.as_view(), name='index'),  # 商品页作为首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
]

dailyfresh/urls.py
# -*-coding:utf-8-*-
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url('admin/', admin.site.urls),
    url('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url('search/', include('haystack.urls')),  # 全文检索框架
    url('user/', include('user.urls', namespace='user')),  # 用户模块
    url('cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url('order/', include('order.urls', namespace='order')),  # 订单模块
    url('', include('goods.urls', namespace='goods')),  # 商品模块
]

templates/df_goods/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class = "{{ type.logo }}">{{ type.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页 列表页 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/df_goods/detail.html
{% extends 'df_goods/base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for sku in same_spu_skus %}
                        <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
            {% csrf_token %}
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart"  sku_id="{{ sku.id }}"  id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="tag_detail">商品介绍</li>
				<li id="tag_comment">评论</li>
			</ul>

			<div class="tab_content" id="tab_detail">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
				</dl>
			</div>

            <div class="tab_content" id="tab_comment" style="display: none;">
				<dl>
                    {% for sku in sku_orders %}
                        <dt>评论时间: {{ sku.update_time }} 用户名:{{ sku.order.user.username }}</dt>
                        <dd>评论内容: {{ sku.comment }}</dd>
                    {% empty %}
                        暂时没有评论信息
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}
{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
      // 商品介绍与评论tag的切换
      $('#tag_detail').click(function () {
          $('#tag_comment').removeClass('active')
          $(this).addClass('active')
          $('#tab_detail').show()
          $('#tab_comment').hide()
      })

      $('#tag_comment').click(function () {
          $('#tag_detail').removeClass('active')
          $(this).addClass('active')
          $('#tab_comment').show()
          $('#tab_detail').hide()
      })


       // 计算商品的小计
        function update_sku_amount() {
            count = $('.num_show').val();
            price = $('.show_pirze').children('em').text();
            // 计算小计
            amount = parseFloat(price) * parseInt(count);
            // 设置商品的小计
            $('.total').children('em').text(amount.toFixed(2)+'元');

        }
       // 商品数量增加
        $('.add').click(function () {
            // 获取商品的数量
            count = $('.num_show').val();
            // 增加1
            count = parseInt(count)+1;
            // 重新设置商品的数量
            $('.num_show').val(count);

            // 重新计算小计
            update_sku_amount()

        });
        // 商品数量减少
       $('.minus').click(function () {
           count = $('.num_show').val();
           count = parseInt(count)-1;
           if (count <= 0) {
               count = 1;
           }
           $('.num_show').val(count);

           update_sku_amount();
       });
       // 手动输入
       $('.num_show').blur(function () {
           count = $(this).val();
           // 校验count 是否合法
           if (isNaN(count) || count.trim().length == 0 || parseInt(count)<=0){
                count = 1;
           }
           $('.num_show').val(parseInt(count));
           update_sku_amount();
       });

		// 获取add_cart a标签左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

			$('#add_cart').click(function(){
            // 获取商品id和商品数目
            count = $('.num_show').val()
            sku_id = $(this).attr('sku_id') // prop attr
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('{% url 'cart:add' %}', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                    'left': $to_y+7,
                    'top': $to_x+7},
                    "fast", function() {
                        $(".add_jump").fadeOut('fast',function(){
                            // 重新设置用户购物车中商品的条目数
                            $('#show_count').html(data.cart_count);
                        });
			        });
                }
                else{
                    alert(data.errmsg)
                }
            })

		})
	</script>
{% endblock bottomfiles %}

templates/df_goods/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in index_banner %}
                    <li><a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banner %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {# 首页展示分类文字商品信息 #}
                {% for banner in type.title_banner %}
                    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/df_goods/list.html
{% extends 'df_goods/base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {# {% for sku in skus_page.object_list %}  如下一样的#}
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
            {# 有上一页 #}
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number%}?sort={{ sort }}">上一页</a>
                {% endif %}

            {% for pageindex in skus_page.paginator.page_range %}
                {% if pageindex == skus_page.number %}
                    <a href="{% url 'goods:list' type.id pageindex %}?sort={{ sort }}" class="active">{{ pageindex }}</a>
                {% else %}
                    <a href="{% url 'goods:list' type.id pageindex %}?sort={{ sort }}">{{ pageindex }}</a>
                {% endif %}
            {% endfor %}

            {# 有下一页 #}
            {% if skus_page.has_next %}
                <a href="{% url 'goods:list' type.id skus_page.next_page_number  %}?sort={{ sort }}">下一页</a>
            {% endif %}
            
			</div>
		</div>
	</div>
{% endblock main_content %}