apps/cart/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from apps.cart.views import CartAddview, CartInfoView, CartUpdateView, CartDeleteView

app_name = 'apps.cart'
urlpatterns = [
    url(r'^add&', CartAddview.as_view(), name='add'),  # 购物车页面
    url(r'^$', CartInfoView.as_view(), name='cart'),  # 显示购物车页
    url(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车数据更新
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 删除购物车中的商品记录
]

apps/order/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from apps.order.views import OrderPlaceView, OrderCommitView, OrderPayView, CheckPayView, OrderCommentView

app_name = 'apps.order'
urlpatterns = [
    url(r'^place$', OrderPlaceView.as_view(), name='place'),  # 提交订单显示
    url(r'^commit$', OrderCommitView.as_view(), name='commit'),  # 订单创建
    url(r'^pay$', OrderPayView.as_view(), name='pay'),  # 订单支付
    url(r'^check$', CheckPayView.as_view(), name='ckeck'),  # 查询支付交易结果
    url(r'^comment/(?P<order_id>.+)$', OrderCommentView.as_view(), name='comment'),  # 订单评论
]

dailyfresh/urls.py
# -*-coding:utf-8-*-
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url('admin/', admin.site.urls),
    url('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url('search/', include('haystack.urls')),  # 全文检索框架
    url('user/', include('user.urls', namespace='user')),  # 用户模块
    url('cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url('order/', include('order.urls', namespace='order')),  # 订单模块
    url('', include('goods.urls', namespace='goods')),  # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.
# cart 使用redis存储

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse

from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin

# Create your views here.
# 添加商品到购物车
# 1) 请求方式，采用ajax post
#    如果涉及到数据的修改(新增，更新，删除),采用post
#    如果涉及到数据的获取, 采用get
# 2) 传递参数：商品id 商品数量


# ajax发起的请求都在后台, 在浏览器中看不到效果
# /cart/add
class CartAddview(View):
    """购物车记录添加"""
    def post(self, request):

        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        # noinspection PyBroadException
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值 -> hget cart_key 属性: cart_key[sku_id]
        # 如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # redis中存在该商品，进行数量累加
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 设置hash中sku_id对应的值
        # hset ->如sku_id存在,更新数据,如sku_id不存在，追加数据
        conn.hset(cart_key, sku_id, count)

        # 获取用户购物车中的条目数
        cart_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'cart_count': cart_count, 'message': '添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    """购物车显示"""
    def get(self, request):
        user = request.user
        # 获取用户购物车的商品信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # {'商品id': 商品数量}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品总数目和总价格
        total_count = 0
        total_price = 0
        # 遍历获取商品信息
        for sku_id, count in cart_dict.items():
            # 根据商品id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            # 动态给sku对象添加一个属性amount,保存商品小计
            sku.amount = amount
            # 动态给sku对象添加一个属性,保存购物车中对应商品的数量
            sku.count = int(count)

            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {'total_count': total_count,
                   'total_price': total_price,
                   'skus': skus}

        return render(request, 'df_cart/cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传递的参数: 商品id(sku_id) 更新商品数量(count)
# /cart/update
class CartUpdateView(View):
    """购物车记录更新"""
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        # noinspection PyBroadException
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理: 更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数{'1':5,'2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数: 商品id(sku_id)
# /cart/delete
class CartDeleteView(View):
    """购物车记录删除"""
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理: 删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数{'1':5,'2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

templates/df_cart/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-购物车{% endblock title %}
{% block page_title %}购物车{% endblock page_title %}
{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
    {% csrf_token %}
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>


    <form method="post" action="{% url 'order:place' %}">
    {% csrf_token%}
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids"  value="{{ sku.id }}"></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock body %}

{# 开始编写jq代码#}
{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    update_page_info()
    // 计算被选中的商品的总件数和总价格
    function update_page_info() {
        var total_count = 0
        var total_price = 0
        // 获取所有被选中的商品的ul元素
        $('.cart_list_td').find(':checked').parents('ul').each(function () {
            // 获取商品的数目和小计
            count = $(this).find('.num_show').val()
            amount = $(this).children('.col07').text()
            // 累加计算商品的总件数和总金额
            total_count += parseInt(count)
            total_price += parseFloat(amount)
        })
        // 设置选中商品的总件数和总金额
        $('.settlements').find('em').text(total_price.toFixed(2))
        $('.settlements').find('b').text(total_count)

    }

    // 更新商品的小计
    function update_sku_amount(sku_ul) {
        // 获取商品的数目和价格
        var price = sku_ul.children('.col05').text()
        var count = sku_ul.find('.num_show').val()
        // 计算商品的小计
        var amount = parseInt(count)*parseFloat(price)
        // 设置商品的小计
        sku_ul.children('.col07').text(amount.toFixed(2)+'元')
    }

    // 全选和全不选
    $('.settlements').find(':checkbox').change(function () {
        // 获取全选checkbox的选中状态
        var is_checked = $(this).prop('checked')
        // 设置商品的checkbox和全选的checkbox状态保持一致
        $('.cart_list_td').find(':checkbox').each(function () {
            $(this).prop('checked', is_checked)
        })
        // 更新页面信息
        update_page_info()
    })

    // 商品的checkbox状态发生改变时，设置全选checkbox的状态改变
    $('.cart_list_td').find(':checkbox').change(function () {
        // 获取所有商品checkbox的数目
        var all_len = $('.cart_list_td').find(':checkbox').length
        // 获取被选中的商品checkbox的数目
        var check_len = $('.cart_list_td').find(':checked').length
        // 判断
        var is_checked = true
        if (check_len < all_len){
            is_checked = false
        }
        // 设置全选checkbox的选中状态
        $('.settlements').find(':checkbox').prop('checked', is_checked)
        // 更新页面信息
        update_page_info()
    })

    // 更新购物车商品的信息
    var error_update = false
    var total_count = 0
    function update_remote_cart_info(sku_id, count) {
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 组织参数
        var params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
        // 更新购物车记录
        // 设置ajax 请求为同步
        $.ajaxSettings.async = false
        // 发起ajax post请求，访问/cart/update, 传递参数:sku_id count
        $.post('/cart/update', params, function (data) {
            if (data.res == 5){
                // 更新成功
                error_update = false
                total_count = data.total_count
            }
            else{
                // 更新失败
                error_update = true
                alert(data.errmsg)
            }
        })
        // 设置ajax请求为异步, false 代表为 同步 true 代表异步
        $.ajaxSettings.async = true
    }

    // 购物车记录的增加
    $('.add').click(function () {
        // 获取商品的id和商品的数目
        var count = $(this).next().val()
        var sku_id = $(this).next().attr('sku_id')

        count = parseInt(count)+1

        // 更新购物车记录
        update_remote_cart_info(sku_id, count)

        // 进行处理
        if (error_update == false){
            // 重新设置商品的数目
            $(this).next().val(count)
            // 更新商品的小计
            update_sku_amount($(this).parents('ul'))
            // 判断是否更新选中商品的总件数和总金额
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面购物车商品的总件数
            $('.total_count').children('em').text(total_count)
        }
    })

    // 购物车记录的减少
    $('.minus').click(function () {
        // 获取商品的id和商品的数目
        var count = $(this).prev().val()
        var sku_id = $(this).prev().attr('sku_id')

        count = parseInt(count)-1
        if (count <= 0){
            return
        }

        // 更新购物车记录
        update_remote_cart_info(sku_id, count)

        // 进行处理
        if (error_update == false){
            // 重新设置商品的数目
            $(this).prev().val(count)
            // 更新商品的小计
            update_sku_amount($(this).parents('ul'))
            // 判断是否更新选中商品的总件数和总金额
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面购物车商品的总件数
            $('.total_count').children('em').text(total_count)
        }
    })

    // 保存用户输入之前购物车中商品的数目
    var pre_count = 0
    $('.num_show').focus(function () {
        pre_count = $(this).val()
    })

    // 手动输入购物车商品数目
    $('.num_show').blur(function () {
        // 获取商品的id和商品的数目
        var count = $(this).val()
        var sku_id = $(this).attr('sku_id')

        // 判断用户输入的商品数目是否合法
        if (isNaN(count) || count.trim().length==0 || parseInt(count)<=0){
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
            return
        }

        // 更新购物车记录
        count = parseInt(count)
        update_remote_cart_info(sku_id, count)

        // 进行处理
        if (error_update == false){
            // 重新设置商品的数目
            $(this).val(count)
            // 更新商品的小计
            update_sku_amount($(this).parents('ul'))
            // 判断是否更新选中商品的总件数和总金额
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面购物车商品的总件数
            $('.total_count').children('em').text(total_count)
        }
        else{
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
        }
    })

    // 删除购物车记录
    $('.cart_list_td').children('.col08').children('a').click(function () {
        // 获取商品的id
        var sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        var sku_ul = $(this).parents('ul')
        // 组织参数
        params = {'sku_id':sku_id, 'csrfmiddlewaretoken':csrf}
        // 发起ajax post请求，访问/cart/delete, 传递参数:sku_id
        $.post('/cart/delete', params, function (data) {
            if (data.res == 3){
                // 删除成功
                // 移除页面商品所在的ul
                sku_ul.remove() // 移除自身和子元素 empty:只移除子元素
                // 获取sku_ul中checkbox的选中状态
                var is_checked = sku_ul.find(':checkbox').prop('checked')
                if (is_checked){
                    // 更新页面信息
                    update_page_info()
                }
                // 设置页面购物车中商品的总件数
                $('.total_count').children('em').text(data.total_count)
            }
            else{
                // 删除失败
                alert(data.errmsg)
            }
        })
    })

    </script>
{% endblock bottomfiles %}