apps/goods/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from apps.goods.views import IndexView, DetailView, ListView

app_name = 'apps.goods'
urlpatterns = [
    url(r'^index/$', IndexView.as_view(), name='index'),  # 商品页作为首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
]

apps/order/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from apps.order.views import OrderPlaceView, OrderCommitView, OrderPayView, CheckPayView, OrderCommentView

app_name = 'apps.order'
urlpatterns = [
    url(r'^place$', OrderPlaceView.as_view(), name='place'),  # 提交订单显示
    url(r'^commit$', OrderCommitView.as_view(), name='commit'),  # 订单创建
    url(r'^pay$', OrderPayView.as_view(), name='pay'),  # 订单支付
    url(r'^check$', CheckPayView.as_view(), name='ckeck'),  # 查询支付交易结果
    url(r'^comment/(?P<order_id>.+)$', OrderCommentView.as_view(), name='comment'),  # 订单评论
]

apps/user/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
# from apps.user import views
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

app_name = 'apps.user'
urlpatterns = [
    # url(r'^register', views.register, name='register'),   # 注册页面
    # url(r'register_handle', views.register_handle, name='register_handle')  # 注册处理

    url(r'^register/$', RegisterView.as_view(), name='register'),  # 注册页面
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    url(r'^login/$', LoginView.as_view(), name='login'),  # 登录
    url(r'^logout/$', LogoutView.as_view(), name='logout'),  # 退出登录

    # 在url配置的时候，调用login_required装饰器，相当于配置的函数是login_required的返回值
    # url(r'^$', login_required(UserInfoView.as_view()), name='user'),  # 用户中心-信息页
    # url(r'^order/$', login_required(UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # url(r'^address/$', login_required(AddressView.as_view()), name='address'),  # 用户中心-地址页

    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    url(r'^address/$', AddressView.as_view(), name='address'),  # 用户中心-地址页

]

dailyfresh/urls.py
# -*-coding:utf-8-*-
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url('admin/', admin.site.urls),
    url('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url('search/', include('haystack.urls')),  # 全文检索框架
    url('user/', include('user.urls', namespace='user')),  # 用户模块
    url('cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url('order/', include('order.urls', namespace='order')),  # 订单模块
    url('', include('goods.urls', namespace='goods')),  # 商品模块
]

apps/goods/models.py
# -*-coding:utf-8-*-
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField


class GoodsType(BaseModel):
    """商品类型模型类"""
    name = models.CharField(max_length=20, verbose_name='种类名称')
    logo = models.CharField(max_length=20, verbose_name='标识')
    image = models.ImageField(upload_to='type', verbose_name='商品类型图片')

    class Meta:
        db_table = 'df_goods_type'
        verbose_name = '商品种类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsSKU(BaseModel):
    """商品SKU模型类"""
    status_choices = (
        (0, '下线'),
        (1, '上线')
    )
    type = models.ForeignKey('GoodsType', on_delete=models.CASCADE, verbose_name='商品种类')
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE, verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.SmallIntegerField(default=1, choices=status_choices, verbose_name='状态')

    class Meta:
        db_table = 'df_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    # def __repr__(self):
    #     return self.name


class Goods(BaseModel):
    """商品SPU模型类"""
    name = models.CharField(max_length=20, verbose_name='商品SPU名称')
    # 富文本类型：带有格式的文本
    detail = HTMLField(blank=True, verbose_name='商品详情')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsImage(BaseModel):
    """商品图片模型类"""
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品')
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    class Meta:
        db_table = 'df_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name


class IndexGoodsBanner(BaseModel):
    """首页轮播商品展示模型类"""
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品')
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexTypeGoodsBanner(BaseModel):
    """首页分类商品展示模型类"""
    DISPLAY_TYPE_CHOICES = (
        (0, '标题'),
        (1, '图片')
    )

    type = models.ForeignKey('GoodsType', on_delete=models.CASCADE, verbose_name='商品类型')
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品SKU')
    display_type = models.SmallIntegerField(default=1, choices=DISPLAY_TYPE_CHOICES, verbose_name='展示类型')
    index = models.SmallIntegerField(default=1, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexPromotionBanner(BaseModel):
    """首页促销活动模型类"""
    name = models.CharField(max_length=20, verbose_name='活动名称')
    url = models.URLField(verbose_name='活动链接')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_promotion'
        verbose_name = '主页促销活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/df_user/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {# 页面的form不设置action, 提交表单时是访问浏览器地址栏中的地址 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

templates/df_user/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles%}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
                    {{ errmsg }}
				</form>
			</div>
		</div>
	</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'base_user_center.html' %}

{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
                                <li><span>联系方式：</span>{{ address.phone }}</li>
                                <li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无</li>
							    <li><span>联系地址：</span>无</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for goods in goods_list %}
				        <li>
                            <a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ goods.price }}</span>
                                <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                        {% empty %}
                            没有浏览记录
                        {% endfor %}
			        </ul>
		        </div>
		</div>
{% endblock right_content %}

templates/df_user/user_center_order.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_content %}
    <div class="right_content clearfix">
        {% csrf_token %}
        <h3 class="common_title2">全部订单</h3>

        {% for order in order_page %}
        <ul class="order_list_th w978 clearfix">
            <li class="col01">{{ order.create_time }}</li>
            <li class="col02">订单号：{{ order.order_id }}</li>
            <li class="col02 stress">{{ order.status_name }}</li>
        </ul>

        <table class="order_list_table w980">
            <tbody>
                <tr>
                    <td width="55%">
                        {% for order_sku in order.order_skus %}
                        <ul class="order_goods_list clearfix">
                            <li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
                            <li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
                            <li class="col03">{{ order_sku.count }}</li>
                            <li class="col04">{{ order_sku.amount }}元</li>
                        </ul>
                        {% endfor %}
                    </td>
                    <td width="15%">{{ order.total_price |add:order.transit_price }}(含运费:{{ order.transit_price }})元</td>
                    <td width="15%">{{ order.status_name }}</td>
                    <td width="15%"><a href="javascript:;" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
                </tr>
            </tbody>
        </table>
        {% endfor %}

        <div class="pagenation">
            {% if order_page.has_previous %}
                <a href="{% url 'user:order' order_page.previous_page_number %}"> < 上一页</a>
            {% endif %}
            {% for pindex in pages %}
                {% if pindex == order_page.number %}
                    <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}
            {% if order_page.has_next %}
                <a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
            {% endif %}
        </div>
    </div>
{% endblock right_content %}

{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $('.oper_btn').each(function () {
            // 获取status
            status = $(this).attr('status')
            if (status == 1){
                $(this).text('去支付')
            }
            else if (status == 4){
                $(this).text('去评价')
            }
            else if (status == 5){
                $(this).text('已完成')
            }
        })


        $('.oper_btn').click(function () {
            // 获取status
            status = $(this).attr('status')
            // 获取订单id
            order_id = $(this).attr('order_id')
            if (status == 1){
                // 进行支付
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                // 组织参数
                params = {'order_id': order_id, 'csrfmiddlewaretoken': csrf}
                // 发起ajax post请求, 访问/order/pay, 传递参数:order_id
                $.post('{% url 'order:pay' %}', params, function (data) {
                    if (data.res == 3){
                        // 引导用户到支付页面
                        window.open(data.pay_url)
                        // 浏览器访问order/check,获取支付交易结果
                        // ajax post  传递参数:order_id
                        $.post('/order/check', params, function () {
                            if (data.res == 3){
                                alert('支付成功')
                                //重新加载
                                location.reload()
                            }
                            else{
                                alert(data.errmsg)
                            }
                        })
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
            else if (status == 4){
                //其他情况
                // 跳转到评价页面
                location.href = "/order/comment/"+order_id
            }
        })
    </script>
{% endblock bottomfiles %}

templates/df_user/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
						    <dd>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone }}</dd>
					    {% else %}
                            <dd>无</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
{% endblock right_content %}